import type { ComparisonPair } from "~/types";

export const beforeAfterData: ComparisonPair[] = [
  {
    id: "ba-01",
    beforeSrc: "/images/before-after/ba-01-before.webp",
    afterSrc: "/images/before-after/ba-01-after.webp",
    beforeLabel: "Smartphone photo",
    afterLabel: "AI studio shot",
    beforeDescription:
      "A product placed on a table, photographed with a phone. Works, but doesn't sell.",
    afterDescription:
      "Same product. Generated in AI with dramatic lighting, perfect backdrop, and zero defects.",
  },
  {
    id: "ba-02",
    beforeSrc: "/images/before-after/ba-02-before.webp",
    afterSrc: "/images/before-after/ba-02-after.webp",
    beforeLabel: "Basic headshot",
    afterLabel: "AI professional portrait",
    beforeDescription:
      "A selfie or quick office photo. Technically acceptable, visually forgettable.",
    afterDescription:
      "Same person. Consistent lighting, background, posture — AI-crafted for maximum professional impact.",
  },
  {
    id: "ba-03",
    beforeSrc: "/images/before-after/ba-03-before.webp",
    afterSrc: "/images/before-after/ba-03-after.webp",
    beforeLabel: "Standard interior photo",
    afterLabel: "AI premium ambiance",
    beforeDescription:
      "A standard daytime photo of a restaurant. Shows the space, but doesn't sell the experience.",
    afterDescription:
      "Same space reimagined: candlelight, golden hour, fine dining atmosphere — generated by AI.",
  },
  {
    id: "ba-04",
    beforeSrc: "/images/before-after/ba-04-before.webp",
    afterSrc: "/images/before-after/ba-04-after.webp",
    beforeLabel: "Generic stock image",
    afterLabel: "Custom AI brand visual",
    beforeDescription:
      "A stock photo from a free website. 10,000 other brands are using the same image.",
    afterDescription:
      "A unique visual generated specifically for your brand. Never seen before. Never will be reused.",
  },
  {
    id: "ba-05",
    beforeSrc: "/images/before-after/ba-05-before.webp",
    afterSrc: "/images/before-after/ba-05-after.webp",
    beforeLabel: "Basic screen recording",
    afterLabel: "AI cinematic video",
    beforeDescription:
      "A simple screen recording or phone video. Gets the message across, barely.",
    afterDescription:
      "A 20-second cinematic product video — VEO-generated, professionally color-graded.",
  },
];
